### ISSUE TITLE
Samtools version naming issue

### ISSUE THREAD

**Issue by mish-su** [tseemann/snippy#450] opened 2021-02-24 23:09 UTC
Hi,

Snippy requires samtools version 1.7. Samtools is now on version 1.11. 

My experience with having samtools/1.10 loaded and running snippy is that it says that my samtools version is too low, which makes sense in a 1.7 > 1.11 way, but does not work with the numbering system of samtools releases.

**Comment by suzlbach** [comment] 2021-03-27 07:53
I think you have snippy version 4.4.v. You should update snippy to at least 4.5 to solve this issue.

**Comment by andersgs** [comment] 2021-04-06 23:02
As @suzlbach suggests, the issue is fixed in version >v4.5.0. Thank you.

**Closed by andersgs** 2021-04-06 23:02 UTC
