### ISSUE TITLE
Read 0 Write 0 read

### ISSUE THREAD

**Issue by XinHuang87** [tseemann/snippy#244] opened 2018-10-11 21:29 UTC
Hi Torsten,

I've tried to run Snippy but it always gave me the following error in snps.log, could you help me out please:
```
### snippy/bin/snippy --cpus 16 --outdir snippy_test_FA --ref GCA_003014415.1_Ca
nd_auris_B11243_genomic.fna --R1 /data/huangx12/XinHuang/Cauris/CDCSecondBatch/m
etagenomics/input/GC_1836.R1.nohuman.r1.fastq --R2 /data/huangx12/XinHuang/Cauri
s/CDCSecondBatch/metagenomics/input/GC_1836.R1.nohuman.r2.fastq

### samtools faidx reference/ref.fa


### bwa index reference/ref.fa

[bwa_index] Pack FASTA... 0.12 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 7.59 seconds elapse.
[bwa_index] Update BWT... 0.08 sec
[bwa_index] Pack forward-only FASTA... 0.08 sec
[bwa_index] Construct SA from BWT and Occ... 2.86 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index reference/ref.fa
[main] Real time: 10.916 sec; CPU: 10.738 sec

### mkdir -p reference/genomes && cp -f reference/ref.fa reference/genomes/ref.fa


### ln -sf reference/ref.fa .


### ln -sf reference/ref.fa.fai .


### mkdir -p reference/ref && gzip -c reference/ref.gff > reference/ref/genes.gff.gz


### bwa mem  -Y -M -R '@RG\tID:snippy_test_FA\tSM:snippy_test_FA' -t 16 reference/ref.fa /data/huangx12/XinHuang/Cauris/CDCSecondBatch/metagenomics/input/GC_1836.R1.nohuman.r1.fastq /data/huangx12/XinHuang/Cauris/CDCSecondBatch/metagenomics/input/GC_1836.R1.nohuman.r2.fastq | samclip --max 10 --ref reference/ref.fa.fai | samtools sort -n -l 0 -T /tmp/huangx12/snippy.38235. --threads 16 -m 500M | samtools fixmate -m - - | samtools sort -l 0 -T /tmp/huangx12/snippy.38235. --threads 16 -m 500M | samtools markdup -T /tmp/huangx12/snippy.38235. -r -s - - > snps.bam

READ 0 WRITTEN 0 
EXCLUDED 0 EXAMINED 0
PAIRED 0 SINGLE 0
DULPICATE PAIR 0 DUPLICATE SINGLE 0
DUPLICATE TOTAL 0

### samtools index snps.bam


### fasta_generate_regions.py reference/ref.fa.fai 405880 > reference/ref.txt


### freebayes-parallel reference/ref.txt 16 -p 2 -P 0 -C 10 --min-repeat-entropy 1.5 --strict-vcf -q 13 -m 60 --min-coverage 10 -F 0.05  -f reference/ref.fa snps.bam > snps.raw.vcf

Error: Failed to set region: -1:0-329,236(*)
ERROR(freebayes): Could not SetRegion to PYGM01000001.1:0..329236
Error: Failed to set region: -1:0-311,833(*)
ERROR(freebayes): Could not SetRegion to PYGM01000002.1:0..311833
Error: Failed to set region: -1:0-281,846(*)
ERROR(freebayes): Could not SetRegion to PYGM01000003.1:0..281846
Error: Failed to set region: -1:0-270,269(*)
```
What am I doing wrong?

Thank you,

Xin

**Comment by tseemann** [comment] 2018-10-11 23:36
It means none of your reads aligned.

This could be because you have Illumina adaptors on them, or the sample is wrong.

Try this:
```
bwa mem-t 16 GCA_003014415.1_Cand_auris_B11243_genomic.fna /data/huangx12/XinHuang/Cauris/CDCSecondBatch/metagenomics/input/GC_1836.R1.nohuman.r1.fastq /data/huangx12/XinHuang/Cauris/CDCSecondBatch/metagenomics/input/GC_1836.R1.nohuman.r2.fastq | samtools sort --threads 16 -m 500M > reads.bam

samtools index reads.bam

samtools flagstat reads.bam
```

What does that say at the end?

**Comment by XinHuang87** [comment] 2018-10-12 19:49
Thank you very much for your prompt response! It looks like there's no read aligned, which is quite strange. I'll look into the reference. 

The output that I got after trying the suggested commands was:

[main] unrecognized command 'mem-t'
0 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
0 + 0 mapped (N/A : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
I must have mistakenly deleted the space between mem and -t.

**Comment by XinHuang87** [comment] 2018-10-12 21:01
I made the bwa to run and there were in fact reads mapped to the reference. At the end was like this:

[bam_sort_core] merging from 32 files and 16 in-memory blocks...
65660257 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
9223 + 0 supplementary
0 + 0 duplicates
9835760 + 0 mapped (14.98% : N/A)
65651034 + 0 paired in sequencing
32825517 + 0 read1
32825517 + 0 read2
9727900 + 0 properly paired (14.82% : N/A)
9822052 + 0 with itself and mate mapped
4485 + 0 singletons (0.01% : N/A)
3930 + 0 with mate mapped to a different chr
2590 + 0 with mate mapped to a different chr (mapQ>=5)

Please also see attached the entire output file. Thank you for any feedback you might have.
[slurm-11229383_output.txt](https://github.com/tseemann/snippy/files/2474597/slurm-11229383_output.txt)

**Comment by tseemann** [comment] 2018-10-13 00:04
This probably means all your reads have Illumina adaptor sequences on them.

This will cause them to all be removed by the `samclip` filter.

Either trim your reads first OR try setting `--maxsoft 250`.

**Comment by PlantDr430** [comment] 2019-02-09 05:41
I am having similar problems with one of my samples. I already completed 23 of 24 samples using snippy-multi but noticed nothing was produced in the core. I searched and found that there were 0 variants found for one sample. Many of these samples also came from the same Illumina sequencing run and were processed in the same way, so I know that they don't have adapters on them because the other 23 samples worked. 

I ran the command:

`snippy --cpus 24 --outdir LM71 --ref reference/Cpur20_1.gbk --R1 LM71_filtered_1P.fastq.gz --R2 LM71_filtered_2P.fastq.gz --maxsoft 300 2>&1 | tee LM71_log.txt`

I've attached the snps.log file and I also attached another log file that I recorded the standard output on (LM71_log.txt). 

In the snps.log file I see errors such as this:

```
Error: Failed to set region: -1:0-224,490(*)
ERROR(freebayes): Could not SetRegion to CAGA010001911:0..224490
Error: Failed to set region: -1:0-533,688(*)
ERROR(freebayes): Could not SetRegion to CAGA010001901:0..533688
Error: Failed to set region: -1:0-694,389(*)
ERROR(freebayes): Could not SetRegion to CAGA010001891:0..694389
Error: Failed to set region: -1:694,389-767,531(*)
ERROR(freebayes): Could not SetRegion to CAGA010001891:694389..767531
Error: Failed to set region: -1:0-2,010(*)
```

Again, I also run re-ran Trimmomatic before this run to check for adapters and even did a Headcrop:20 just in case. However, I also ran:

`bwa mem -t 16 LM71/reference/ref.fa LM71_filtered_1P.fastq.gz LM71_filtered_2P.fastq.gz | samtools sort --threads 16 -m 500M > reads.bam`

as you suggested above and got:

```
stephenwyka@bspmgenomics:/data/wyka/snpcalling$ samtools index reads.bam
stephenwyka@bspmgenomics:/data/wyka/snpcalling$ samtools flagstat reads.bam
38957854 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
597470 + 0 supplementary
0 + 0 duplicates
36028160 + 0 mapped (92.48% : N/A)
38360384 + 0 paired in sequencing
19180192 + 0 read1
19180192 + 0 read2
33354274 + 0 properly paired (86.95% : N/A)
35080686 + 0 with itself and mate mapped
350004 + 0 singletons (0.91% : N/A)
1404026 + 0 with mate mapped to a different chr
1054282 + 0 with mate mapped to a different chr (mapQ>=5)
```

I did notice in the standard output that I was getting this error:

```
[bam_sort_core] merging from 16 files and 16 in-memory blocks...
[E::hts_open_format] Failed to open file /tmp/snippy.29629..0012.bam
[E::hts_open_format] Failed to open file /tmp/snippy.29629..0013.bam
[E::hts_open_format] Failed to open file /tmp/snippy.29629..0015.bam
[E::hts_open_format] Failed to open file /tmp/snippy.29629..0011.bam
[E::hts_open_format] Failed to open file /tmp/snippy.29629..0014.bam
[E::hts_open_format] Failed to open file /tmp/snippy.29629..0004.bam
[E::hts_open_format] Failed to open file /tmp/snippy.29629..0009.bam
[E::hts_open_format] Failed to open file /tmp/snippy.29629..0002.bam
[E::hts_open_format] Failed to open file /tmp/snippy.29629..0008.bam
[E::hts_open_format] Failed to open file /tmp/snippy.29629..0005.bam
[E::hts_open_format] Failed to open file /tmp/snippy.29629..0003.bam
[E::hts_open_format] Failed to open file /tmp/snippy.29629..0001.bam
[E::hts_open_format] Failed to open file /tmp/snippy.29629..0010.bam
[E::hts_open_format] Failed to open file /tmp/snippy.29629..0000.bam
samtools sort: failed to create temporary file "/tmp/snippy.29629..0000.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.29629..0001.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.29629..0002.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.29629..0003.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.29629..0004.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.29629..0005.bam": File exists
[E::hts_open_format] Failed to open file /tmp/snippy.29629..0006.bam
samtools sort: failed to create temporary file "/tmp/snippy.29629..0006.bam": File exists
[E::hts_open_format] Failed to open file /tmp/snippy.29629..0007.bam
samtools sort: failed to create temporary file "/tmp/snippy.29629..0007.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.29629..0008.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.29629..0009.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.29629..0010.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.29629..0011.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.29629..0012.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.29629..0013.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.29629..0014.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.29629..0015.bam": File exists
```
But I don't know why I would be getting this using snippy if it didn't occur when I can samtools sort in the piped command above.

[LM71_log.txt](https://github.com/tseemann/snippy/files/2847556/LM71_log.txt)
[snps.log](https://github.com/tseemann/snippy/files/2847557/snps.log)

**Comment by housw** [comment] 2019-04-01 17:14
Hi Torsten, 

I can confirm the same issue as @PlantDr430 has, it didn't help even I tried to remove the temporary files before running snippy.

```
[main] Real time: 1061.070 sec; CPU: 12357.464 sec
[bam_sort_core] merging from 32 files and 16 in-memory blocks...
[E::hts_open_format] Failed to open file /tmp/snippy.8..0000.bam
samtools sort: failed to create temporary file "/tmp/snippy.8..0000.bam": File exists
[E::hts_open_format] Failed to open file /tmp/snippy.8..0010.bam
[E::hts_open_format] Failed to open file /tmp/snippy.8..0007.bam
[E::hts_open_format] Failed to open file /tmp/snippy.8..0008.bam
[E::hts_open_format] Failed to open file /tmp/snippy.8..0015.bam
[E::hts_open_format] Failed to open file /tmp/snippy.8..0012.bam
[E::hts_open_format] Failed to open file /tmp/snippy.8..0014.bam
[E::hts_open_format] Failed to open file /tmp/snippy.8..0006.bam
[E::hts_open_format] Failed to open file /tmp/snippy.8..0013.bam
[E::hts_open_format] Failed to open file /tmp/snippy.8..0002.bam
[E::hts_open_format] Failed to open file /tmp/snippy.8..0009.bam
[E::hts_open_format] Failed to open file /tmp/snippy.8..0004.bam
[E::hts_open_format] Failed to open file /tmp/snippy.8..0005.bam
[E::hts_open_format] Failed to open file /tmp/snippy.8..0003.bam
[E::hts_open_format] Failed to open file /tmp/snippy.8..0001.bam
samtools sort: failed to create temporary file "/tmp/snippy.8..0001.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.8..0002.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.8..0003.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.8..0004.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.8..0005.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.8..0006.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.8..0007.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.8..0008.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.8..0009.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.8..0010.bam": File exists
[E::hts_open_format] Failed to open file /tmp/snippy.8..0011.bam
samtools sort: failed to create temporary file "/tmp/snippy.8..0011.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.8..0012.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.8..0013.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.8..0014.bam": File exists
samtools sort: failed to create temporary file "/tmp/snippy.8..0015.bam": File exists
READ 0 WRITTEN 0 
EXCLUDED 0 EXAMINED 0
PAIRED 0 SINGLE 0
DULPICATE PAIR 0 DUPLICATE SINGLE 0
DUPLICATE TOTAL 0
```

I got snps only for around half of my samples, the others failed with no snps reported, but all the reads were quality controlled with the same pipleline.  

Any idea?

Thanks, 
Shengwei

**Comment by SioStef** [comment] 2019-10-11 13:55
Same problem here! I noticed that all failing datasets where the largest one (>12M reads). I increased the allocated RAM using the --ram option (default is 8G) and the problem solved for me. It seems samtools fails for some reason when not enough resources are allowed? See also here [https://github.com/samtools/samtools/issues/603](url)

**Comment by tseemann** [comment] 2019-10-12 08:19
@SioStef that could be the problem indeed. default is 8 GB RAM, and i allocate 1/2 of it to samtools, but samtools gets run in a pipe twice, so if you only have 8 GB RAM it probably won't work.

@housw there was also bugs fixed in recent versions to do with ram/threads and temp folder. you will need to have enough space in `--tmpdir` to write out 2 BAM files.

**Comment by housw** [comment] 2019-11-01 17:51
Hi Torsten, 

I was using `snippy 4.3.6`, the latest version works great now. 

Thanks, 
Shengwei

**Comment by tseemann** [comment] 2019-11-03 05:55
@housw great news! thank you for reporting back to me.

**Closed by tseemann** 2019-11-03 05:55 UTC
Labels: help wanted
